name: Test deployment

on:
  pull_request:
    branches: [main]
    paths: [www/**]

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: npm
          cache-dependency-path: www/package-lock.json
      - name: Test build
        working-directory: www
        run: |
          npm ci
          npm run build